name: fomms-workshop
channels:
  - conda-forge
  - bioconda
dependencies:
  - mbuild
  - foyer
  - gmso
  - mdtraj
  - nglview
  - hoomd
  - mosdef_cassandra
  - gromacs
  - py3dmol
  - matplotlib
  - panedr
  - signac
  - signac-flow 
  - sigac-dashboard
  - pandas
  - numpy
  - h5py
  - pip
  - pip:
    - git+https://github.com/mosdef-hub/gmso.git@develop
